### ISSUE TITLE
Failed to install 'cordova-spotify':Error: spawn EACCES

### ISSUE THREAD

**Issue by andreasseiler** [Festify/cordova-spotify#32] opened 2017-07-20 17:02 UTC
Hi,

I'm trying to install your plugin in my Meteor App (current Meteor version 1.5.1) and it gives me the above error ... Failed to install 'cordova-spotify':Error: spawn EACCES. I'm running Ubuntu 16.04 LTS. 

Did anyone else run into this error? I tried modifying the permissions in all related folders.

Regards,
Andi

**Comment by NeoLegends** [comment] 2017-07-20 17:04
Any more detail about which file is accessed? This is probably a duplicate of #31.

**Comment by andreasseiler** [comment] 2017-07-20 17:21
I'm not 100% sure but I'm assuming it has to do with creating the folders (plugins/cordova-spotify/src/android/spotify-auth and plugins/cordova-spotify/src/android/spotify-sdk) in the install-android.sh since it aborts before these folders get created

**Comment by andreasseiler** [comment] 2017-07-20 18:14
Tried to install it from local file system with a modified install script, but I keep running into erros with missing files

Probably have to wait until you convert the install scripts to JS, I would be glad to help, but I'm kind of a noob when it comes to Android Development ... :(

**Comment by NeoLegends** [comment] 2017-07-20 18:52
Just something that came to my mind right now: did you ensure that there are no spaces in the projecg folder path? I might have fixed these issues just now, but we've had problems with that in the past.

Could you try installing the plugin from git directly? I just made a path-related commit that isn't published yet.

**Comment by andreasseiler** [comment] 2017-07-20 19:18
One thing, could you create a new release from the current develop branch? With the current status it seems to work, but I can only use it as a plugin correctly with a release version.

Thanks in advance!

**Comment by Remco75** [comment] 2017-07-21 08:46
I experience the same. Installing with `ionic cordova plugin add https://github.com/Festify/cordova-spotify` fixes it for me...(see #21 ) Releasing to NPM would be nice indeed!

**Comment by NeoLegends** [comment] 2017-07-21 09:08
@andreasseiler @Remco75 Got the new release out.

**Comment by NeoLegends** [comment] 2017-08-22 17:46
So everything seems to be working now? I'll just close this. Feel free to reopen if the problem persists. :)

**Closed as completed by NeoLegends** 2017-08-22 17:46 UTC
Labels: bug, duplicate
